version: 0.2

phases:
  install:
    runtime-versions:
      php: latest  # Adjust based on your WordPress/PHP version compatibility
    commands:
      - echo "Installing dependencies"
      - apt-get install -y zip unzip
  pre_build:
    commands:
      - echo "Running pre-build tasks"
      - php --version
      - echo "Linting PHP files"
      - find . -name "*.php" -print0 | xargs -0 -n1 php -l  # Optional PHP linting
  build:
    commands:
      - echo "Zipping the WordPress application"
      - zip -r wordpress.zip wp-content
  post_build:
    commands:
      - echo "Copying artifacts to the output directory"
      - mkdir -p artifacts
      - mv wordpress.zip artifacts/

artifacts:
  files:
    - artifacts/wordpress.zip
    - scripts/*
    - appspec.yml